const { registerUser } = require('../controller/register')
// const activateAcct = require('../controller/activate')
// const deleteAccount = require('../controller/delete')
// const deactivateAcct = require('../controller/deactivate')
//const validate = require('../middleware/validateAct')
//const getAllAccount = require('../controller/getallAcct')
const createAcct = require('../controller/createAcct')
const loginUser = require('../controller/login')
const validator = require('../middleware/validate')
const ValidateCreateAcct = require('../middleware/validate-account')
// const creatAdmin = require('../controller/admin')
// const createStaff = require('../controller/cashier')
// const  getSingleAccount   = require('../controller/acct')
//const creditUser = require('../controller/credit')
const resetPassword = require('../controller/reset')
//const debitUser = require('../controller/debit')
const contactMe = require('../controller/contact')
//const Authorization = require('../middleware/isAdmin')
const express = require('express')
const app = require('../app')
//const contactMe = require('../controller/contact')
const validateContact = require('../middleware/contactVal')
const authenticateToken = require('../middleware/Auth')
const router = express.Router()

router.route('/register').post(validator.createUser, registerUser)
// router.route('/register').get(authenticateToken, Authorization, getAllUsers)
router.route('/login').post(validator.createUser, loginUser)
router
  .route('/create-acct')
  .post(ValidateCreateAcct.createAccout, authenticateToken, createAcct)
// router
//   .route('/activate/:accountId')
//   .patch(validate.activate, Authorization, activateAcct)
// router.route('/deactivate/:accountId').patch(validate.activate, deactivateAcct)
// router.route('/delete/:accountId').delete(validate.activate, deleteAccount)
//router.route('/register').post(getAllUsers)
// router.route('/accounts').get(authenticateToken, Authorization, getAllAccount)
// router.route('/create-admin/:id').patch(creatAdmin)
// router.route('/create-cashier/:id').patch(createStaff)
// router.route('/account/:accountNumber').get(getSingleAccount)
// router.route('/account').get(getAllBankAccount)
// // router.route('/credit').post(creditUser)
// // router.route('/debit').post(debitUser)
router.route('/contact').post(validateContact.contact, contactMe)
router.route('/reset/:userid').patch(authenticateToken, resetPassword)
module.exports = router
